// Package docs Code generated by swag; DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/register": {
            "post": {
                "description": "Crea una nueva cuenta de usuario y retorna un JWT",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Registrar nuevo usuario",
                "parameters": [
                    {
                        "description": "Datos del usuario",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {"type": "string", "example": "usuario@ejemplo.com"},
                                "nombre_de_usuario": {"type": "string", "example": "miusuario"},
                                "contraseña": {"type": "string", "example": "password123"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {"description": "Usuario registrado exitosamente"},
                    "400": {"description": "Datos inválidos"},
                    "409": {"description": "Email o usuario ya existe"}
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Autentica un usuario y devuelve un JWT",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Iniciar sesión",
                "parameters": [
                    {
                        "description": "Credenciales de login",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {"type": "string", "example": "usuario@ejemplo.com"},
                                "contraseña": {"type": "string", "example": "password123"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "Login exitoso"},
                    "400": {"description": "Datos inválidos"},
                    "401": {"description": "Credenciales incorrectas"}
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Genera un nuevo token JWT basado en uno válido existente",
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Renovar token JWT",
                "security": [{"BearerAuth": []}],
                "responses": {
                    "200": {"description": "Token renovado exitosamente"},
                    "401": {"description": "Token inválido o expirado"}
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Invalida el token JWT actual agregándolo a la blacklist",
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Cerrar sesión",
                "security": [{"BearerAuth": []}],
                "responses": {
                    "200": {"description": "Sesión cerrada exitosamente"},
                    "401": {"description": "Token inválido"}
                }
            }
        },
        "/auth/change-password": {
            "post": {
                "description": "Cambia la contraseña del usuario autenticado",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Cambiar contraseña",
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {
                        "description": "Contraseñas",
                        "name": "passwords",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "contraseña_actual": {"type": "string", "example": "password123"},
                                "nueva_contraseña": {"type": "string", "example": "newpassword456"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "Contraseña actualizada exitosamente"},
                    "400": {"description": "Datos inválidos"},
                    "401": {"description": "Contraseña actual incorrecta"}
                }
            }
        },
        "/users/profile": {
            "get": {
                "description": "Obtiene los datos del perfil del usuario autenticado",
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Obtener perfil del usuario",
                "security": [{"BearerAuth": []}],
                "responses": {
                    "200": {"description": "Perfil del usuario"},
                    "401": {"description": "No autenticado"},
                    "404": {"description": "Usuario no encontrado"}
                }
            },
            "put": {
                "description": "Actualiza los datos del perfil del usuario autenticado",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Actualizar perfil del usuario",
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {
                        "description": "Datos a actualizar",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {"type": "string", "example": "nuevo@ejemplo.com"},
                                "nombre_de_usuario": {"type": "string", "example": "nuevousuario"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "Perfil actualizado"},
                    "400": {"description": "Datos inválidos"},
                    "409": {"description": "Email o usuario ya existe"}
                }
            },
            "delete": {
                "description": "Elimina permanentemente la cuenta del usuario autenticado",
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Eliminar cuenta del usuario",
                "security": [{"BearerAuth": []}],
                "responses": {
                    "200": {"description": "Cuenta eliminada"},
                    "401": {"description": "No autenticado"},
                    "404": {"description": "Usuario no encontrado"}
                }
            }
        },
        "/admin/users": {
            "get": {
                "description": "Obtiene una lista paginada de todos los usuarios",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Listar usuarios (Admin)",
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {"type": "integer", "default": 1, "description": "Número de página", "name": "page", "in": "query"},
                    {"type": "integer", "default": 10, "description": "Tamaño de página", "name": "page_size", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "Lista de usuarios"},
                    "401": {"description": "No autenticado"},
                    "403": {"description": "No autorizado"}
                }
            }
        },
        "/admin/users/{id}": {
            "get": {
                "description": "Obtiene los datos de un usuario específico por su ID",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Obtener usuario por ID (Admin)",
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {"type": "string", "description": "ID del usuario (UUID)", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "Datos del usuario"},
                    "400": {"description": "ID inválido"},
                    "404": {"description": "Usuario no encontrado"}
                }
            }
        },
        "/health": {
            "get": {
                "description": "Verifica el estado del servidor, base de datos y Redis",
                "produces": ["application/json"],
                "tags": ["health"],
                "summary": "Health check del servidor",
                "responses": {
                    "200": {"description": "Todos los servicios funcionando"},
                    "503": {"description": "Algún servicio no disponible"}
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Ingrese el token con el prefijo Bearer. Ejemplo: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Go JWT Backend API",
	Description:      "API REST de autenticación y gestión de usuarios con JWT",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
